### ISSUE TITLE
Error: 'failed to get private key from bytes'

### ISSUE THREAD

**Issue by QiuDaniel** [zksync-sdk/zksync-sdk-swift#2]
I exported the private key from a test metamask account, used this private key to generate a ZKPrivateKey object, and then used this object to obtain the public key, but the function threw an error: failed to get private key from bytes.

`thread '<unnamed>' panicked at 'failed to get private key from bytes: NotInField("private key")', zks-crypto-c/src/utils.rs:144:53`

**Comment by StanislavBreadless** [comment]
Hi! Could you please show us the code that throws an error? 

Make sure that you are not using the ETH private key as a zkSync private key and indeed generate the former.

**Comment by StanislavBreadless** [comment]
@QiuDaniel Closing the issue. Feel free to reopen if the error repeats.
